spring.datasource.url=jdbc:postgresql://localhost:5432/db_transportes
spring.datasource.username=app_admin
spring.datasource.password=Admin1234!
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=transportes-bo-secret-key-muy-largo-para-firmar-tokens-jwt-con-hmacsha256-algoritmo
jwt.expiration=86400000

# Jackson - Evitar errores de serialización con proxies de Hibernate
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.serialization.FAIL_ON_SELF_REFERENCES=false
